name: Phantom
version: 4
main: org.cyberpwn.phantom.Phantom
description: Phantom - Another Damn API
author: cyberpwn
authors: [cyberpwn]
website: http://cyberpwn.org/docs/phantom/
commands:
  phantom:
    aliases: [ph, p, phan, pha]