name: Phantom
version: ${project.version}
main: org.phantomapi.Phantom
description: ${project.description}
author: cyberpwn
authors: [cyberpwn]
depend: [ProtocolLib, PlaceholderAPI, Citizens, FastAsyncWorldEdit, WorldEdit]
website: http://phantomapi.org/
load: POSTWORLD
database: false
commands:
  phantom:
    aliases: [ph, p, phan, pha, nova, nov, wraith, wra, wr, ghost, gh]
    description: The only damn command you need