name: Phantom
version: X6
main: org.phantomapi.Phantom
description: Phantom - Another Damn API
author: cyberpwn
authors: [cyberpwn]
depend: [ProtocolLib, PlaceholderAPI]
softdepend: [FastAsyncWorldEdit]
website: http://phantomapi.org/
commands:
  phantom:
    aliases: [ph, p, phan, pha]