name: Phantom
version: X9
main: org.phantomapi.Phantom
description: Phantom - Another Damn API
author: cyberpwn
authors: [cyberpwn]
depend: [ProtocolLib, PlaceholderAPI, FastAsyncWorldEdit, WorldEdit]
website: http://phantomapi.org/
commands:
  phantom:
    aliases: [ph, p, phan, pha]