name: Phantom
version: X2
main: org.phantomapi.Phantom
description: Phantom - Another Damn API
author: cyberpwn
authors: [cyberpwn]
depend: [ProtocolLib]
website: http://phantomapi.org/
commands:
  phantom:
    aliases: [ph, p, phan, pha]